In [13]:
#classifier
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast',
           'Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']

temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild',
        'Cool','Mild','Mild','Mild','Hot','Mild']

play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes',
      'Yes','Yes','Yes','Yes','No']
le = preprocessing.LabelEncoder()

weather_encoded = le.fit_transform(weather)
weather_encoded

array([2, 2, 0, 1, 1, 1, 0, 2, 2, 1, 2, 0, 0, 1])

In [14]:
temp_encoded = le.fit_transform(temp)

temp_encoded

array([1, 1, 1, 2, 0, 0, 0, 2, 0, 2, 2, 2, 1, 2])

In [15]:
label = le.fit_transform(play)
label

array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [16]:
features=tuple(zip(weather,temp,play))
features

(('Sunny', 'Hot', 'No'),
 ('Sunny', 'Hot', 'No'),
 ('Overcast', 'Hot', 'Yes'),
 ('Rainy', 'Mild', 'Yes'),
 ('Rainy', 'Cool', 'Yes'),
 ('Rainy', 'Cool', 'No'),
 ('Overcast', 'Cool', 'Yes'),
 ('Sunny', 'Mild', 'No'),
 ('Sunny', 'Cool', 'Yes'),
 ('Rainy', 'Mild', 'Yes'),
 ('Sunny', 'Mild', 'Yes'),
 ('Overcast', 'Mild', 'Yes'),
 ('Overcast', 'Hot', 'Yes'),
 ('Rainy', 'Mild', 'No'))

In [17]:
totalCases = len(features)
# Probablity of Play 
pY = 0
# Probablity of Not Play 
pN = 0

# Probablity of Yes and Sunny
p_S_Y = 0;
# Probablity of Yes and OverCast
p_O_Y = 0;
# Probablity of Yes and Rainy
p_R_Y = 0;


# Probablity of Yes and Hot
p_H_Y = 0;
# Probablity of Yes and Mild
p_M_Y = 0;
# Probablity of Yes and Cool
p_C_Y = 0;

# Probablity of No and Sunny
p_S_N = 0;
# Probablity of No and OverCast
p_O_N = 0;
# Probablity of No and Rainy
p_R_N = 0;


# Probablity of No and Hot
p_H_N = 0;
# Probablity of No and Mild
p_M_N = 0;
# Probablity of No and Cool
p_C_N = 0;



for index, item in enumerate(features):
    
    if item[2] == 'Yes':
      if item[0] == 'Sunny':
        p_S_Y+=1
      elif item[0] == 'Overcast':
        p_O_Y+=1
      else:
        p_R_Y+=1

      if item[1] == 'Hot':
        p_H_Y+=1
      elif item[1] == 'Mild':
        p_M_Y+=1
      else:
        p_C_Y+=1

      pY+=1

    if item[2] == 'No':
      if item[0] == 'Sunny':
        p_S_N+=1
      elif item[0] == 'Overcast':
        p_O_N+=1
      else:
        p_R_N+=1

      if item[1] == 'Hot':
        p_H_N+=1
      elif item[1] == 'Mild':
        p_M_N+=1
      else:
        p_C_N+=1


      pN+=1

p_S_Y /= pY
p_O_Y /= pY
p_R_Y /= pY

p_H_Y /= pY
p_M_Y /= pY
p_C_Y /= pY
pY = pY/totalCases

p_S_N /= pN
p_O_N /= pN
p_R_N /= pN

p_H_N /= pN
p_M_N /= pN
p_C_N /= pN
pN /= totalCases

# probablity of play when weather is Sunny and temp is Mild
p_S_M =(p_S_Y* p_M_Y * pY) + (p_S_N * p_M_N * pN)
p_Y_SM = p_S_Y * p_M_Y * pY / p_S_M


# probablity of play when weather is Overcast and temp is Mild
p_O_M =(p_O_Y* p_M_Y * pY) + (p_O_N * p_M_N * pN)
p_Y_OM = p_O_Y * p_M_Y * pY / p_O_M


# probablity of play when weather is Sunny and temp is Hot
p_S_H = (p_S_Y * p_H_Y * pY) + (p_S_N * p_H_N * pN)
p_Y_SH = p_S_Y * p_H_Y * pY / p_S_H

p_Y_SM

0.425531914893617

In [18]:
features_encoded=tuple(zip(weather_encoded,temp_encoded))
features_encoded

((2, 1),
 (2, 1),
 (0, 1),
 (1, 2),
 (1, 0),
 (1, 0),
 (0, 0),
 (2, 2),
 (2, 0),
 (1, 2),
 (2, 2),
 (0, 2),
 (0, 1),
 (1, 2))

In [19]:
model = MultinomialNB()

model.fit(features_encoded,label)

predicted_Overcast_Mild = model.predict([[0,2]])
predicted_Overcast_Mild

predicted_Overcast_Hot = model.predict([[0,1]])
predicted_Overcast_Hot

predicted_Sunny_Mild = model.predict([[2,2]])
predicted_Sunny_Mild

array([1])

In [20]:
#classifier
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()
iris.feature_names
iris.target_names
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
newdata = iris.data[50:,:]
newtarget = iris.target[50:]

from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(newdata,newtarget,test_size = .30, random_state=5)

import numpy as np

gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

from sklearn import metrics

metrics.accuracy_score(target_test, target_pred)

0.9

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[16,  1],
       [ 2, 11]])

In [23]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: 0.8888888888888888
recall: 0.9411764705882353


In [24]:
#excercise
import numpy as np 
import pandas as pd
from sklearn.preprocessing import LabelEncoder,OneHotEncoder

datasets = pd.read_csv('Dataset2.csv') 
print("\nData :\n",datasets)
print("\nData statistics\n",datasets.describe())

FileNotFoundError: ignored

In [ ]:
features = datasets.iloc[:,:-1]
play = datasets.iloc[:,-1].values

oneHotEncoder = OneHotEncoder()
x = oneHotEncoder.fit_transform(features.Outlook.values.reshape(-1,1)).toarray()
x

In [ ]:
dfOneHot = pd.DataFrame(x, columns = features.Outlook.unique().tolist()) 
df = pd.concat([features, dfOneHot], axis=1) #column
#droping the country column 
df= df.drop(['Outlook'], axis=1) 
#printing to verify 
print(df.head())

# datasets.Outlook.unique().tolist()
